name: Tests - Nightly

on:
  pull_request:
  push:
    branches:
      - main


jobs:
  build-nightly:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        rustflags:
          - '-C target-cpu=native'
          - '-C target-cpu=native -C target-feature=-avx2'
          - '-C target-cpu=native -C target-feature=-avx2,-pclmulqdq'
        features:
          - '--no-default-features'
          - ''
          - '--features value-no-dup-keys'
          - '--features known-key'
          - '--features 128bit'
          - '--features beef'
          - '--features beef,known-key'
          - '--features approx-number-parsing'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: miri

    - name: Build
      env:
        RUSTFLAGS: ${{ matrix.rustflags }}
      run: cargo build ${{ matrix.features }}

    - name: Run tests
      env:
        RUSTFLAGS: ${{ matrix.rustflags }}
      run: cargo test ${{ matrix.features }}

    # we can't use miri any more, something broke.
    # - name: Run miri
    #   env:
    #     RUSTFLAGS: ${{ matrix.rustflags }}
    #   run: cargo miri test ${{ matrix.features }}

    - name: Run tests (alloc)
      if: matrix.features == ''
      env:
        RUSTFLAGS: ${{ matrix.rustflags }}
      run: cargo test --features alloc
